server:
  port: 8081
spring:
  # 数据源
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.whyat.top:3307/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    password: 81654660
  # security
#  security:
#    user:
#      name: whyat
#      password: 123
  #redis
  redis:
    host: www.whyat.top
    port: 6380
  #热部署
  devtools:
    remote:
      restart:
        enabled: true
whyat:
  jwt:
    tokenName: Authorization
    expire: 604800 #过期时间：7天，单位秒
    secret: sadu5sadfgfazxcfasd51zxcasad15ad #随机32位字符串密钥
mybatis-plus:
 mapper-locations: classpath*:/mapper/**Mapper.xml
